name: Deploy service to AWS Lambda

on: 
  push: 
    branches: 
      - main

jobs:
  build-and-upload-binary:
    name: Check the Python script and upload to Amazon S3
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4.7.1
        with:
          python-version: '3.10' 
      - run: python -m py_compile handler.py
      - run: sudo apt install -y zip && zip demo.zip handler.py

      - uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::574563284495:role/gha
      - run: aws s3api put-object --bucket lambda-20231102013812622900000001 --key demo.zip --body demo.zip --checksum-algorithm SHA256
